version: "3.7"
services:
  redis:
    image: redis
    ports: 
      - 6379
    volumes: 
      - ./data:/data
  server:
    image: duelingo-server
    ports: 
      - 3000:3000
    links:
      - redis
  web:
    image: duelingo-web
    ports: 
      - 8080:8080
    links:
      - server
    user: root
    stdin_open: true
    tty: true