version: "3.7"
services:
  redis:
    image: redis
    container_name: redis
    ports: 
      - 6379
    volumes: 
      - ./data:/data
    networks:
      - duelingo
  server:
    build: ./server
    image: duelingo-server
    container_name: duelingo-server
    ports: 
      - 3000:3000
    links:
      - redis
    stdin_open: true
    tty: true
    networks: 
      - duelingo
  web:
    build: ./web
    image: duelingo-web
    container_name: duelingo-web
    ports: 
      - 8080:8080
    links:
      - server
    user: root
    stdin_open: true
    tty: true
    networks: 
      - duelingo
networks:
  duelingo:
    name: duelingo